// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20260106130757_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Isactive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Isactive = false,
                            Price = 20000m,
                            ProductName = "Iphone14"
                        },
                        new
                        {
                            ProductId = 2,
                            Isactive = true,
                            Price = 50000m,
                            ProductName = "Iphone15"
                        },
                        new
                        {
                            ProductId = 3,
                            Isactive = false,
                            Price = 90000m,
                            ProductName = "Iphone16"
                        },
                        new
                        {
                            ProductId = 4,
                            Isactive = true,
                            Price = 120000m,
                            ProductName = "Iphone17"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
